language: node_js
node_js:
  - "9"
  - "8"
  - "7"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'if [ -n "${PACKAGE-}" ]; then cd "packages/${PACKAGE}"; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.9" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
  - 'if [ -n "${ESLINT}" ]; then npm install --no-save "eslint@${ESLINT}"; fi'
script:
  - 'if [ -n "${PREPUBLISH-}" ]; then npm run prepublish; elif [ -n "${LINT-}" ]; then npm run lint; else npm run travis; fi'
sudo: false
env:
  matrix:
    - 'TEST=true ESLINT=4 PACKAGE=eslint-config-axept'
    - 'TEST=true ESLINT=4 PACKAGE=eslint-config-axept-base'
    - 'TEST=true ESLINT=4 PACKAGE=eslint-config-axept-flow'
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=4 PACKAGE=eslint-config-axept
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=4 PACKAGE=eslint-config-axept-base
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=4 PACKAGE=eslint-config-axept-flow
    - node_js: "lts/*"
      env: LINT=true
  allow_failures:
    - node_js: "9"
    - node_js: "7"
    - env: PREPUBLISH=true ESLINT=4 PACKAGE=eslint-config-axept
    - env: PREPUBLISH=true ESLINT=4 PACKAGE=eslint-config-axept-base
    - env: PREPUBLISH=true ESLINT=4 PACKAGE=eslint-config-axept-flow
